VERILATOR   = verilator
V_FLAGS     = --binary --sv --trace --timing --timescale 1ns/1ps --Mdir $(BUILD_DIR)

INC_DIR     = -Irtl/packages -Irtl/lib -Irtl/core
SIM_DIR     = sim
BUILD_DIR   = $(SIM_DIR)/build
RTL_DIR     = src/rtl
TB_DIR      = src/tb

TOP        ?= fault_injection_detection_core
BIN         = $(BUILD_DIR)/Vtb_$(TOP)
SRCS        = $(shell find $(RTL_DIR) -name "*.sv") \
              $(TB_DIR)/tb_$(TOP).sv

all: clean compile sim

compile:
	$(VERILATOR) $(V_FLAGS) $(INC_DIR) $(SRCS) --top-module tb_$(TOP)

sim:
	./$(BIN)

wave:
	gtkwave $(SIM_DIR)/tb_$(TOP).vcd

clean:
	rm -rf $(BUILD_DIR) $(SIM_DIR)/*.vcd

.PHONY: all compile sim wave clean