// Auto-generated by LibreLane
module trc_top(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  inout vss,
  inout vcc,
  inout gnd,
  inout vdd,
  inout vss3v3,
  input iCLK,
  input iRST,
  input iSPI_CS,
  input iSPI_SCK,
  input iSPI_MOSI,
  input oSPI_MISO_IN,
  output oSPI_MISO_OUT,
  output oSPI_MISO_OE,
  output oSPI_MISO_IE,
  output oSPI_MISO_PU,
  output oSPI_MISO_PD,
  output oSPI_MISO_CS,
  output oSPI_MISO_SL,
  input oINTERRUPT_IN,
  output oINTERRUPT_OUT,
  output oINTERRUPT_OE,
  output oINTERRUPT_IE,
  output oINTERRUPT_PU,
  output oINTERRUPT_PD,
  output oINTERRUPT_CS,
  output oINTERRUPT_SL
);
endmodule
